### ISSUE TITLE
[Feature]: Add Non-MM Supervisor Standalone MM X64 Binaries

### ISSUE THREAD

**Issue by makubacki** [microsoft/mu_crypto_release#111]
### Feature Overview

Currently, the X64 Standalone MM binaries assume the MM Supervisor is being used. Another set of binaries built against the `StandaloneMmPkg` libraries should also be created.

### Solution Overview

Build another set of X64 Standalone MM binaries against `StandaloneMmPkg`.

### Urgency

Medium

### Are you going to implement the feature request?

Someone else needs to implement the feature

### Do you need maintainer feedback?

No maintainer feedback needed

**Comment by MarcChen46** [comment]
Hi @makubacki, may I know if there is an ETA when it will be done? currently we are using our own pre-build binary as a short-term w/a, we would like to consume the formal binary from MU's CryptoBinPkg.

**Comment by makubacki** [comment]
If no one picks it up by next week, I can work on it. In that case it would 12/6.
