### ISSUE TITLE
[Feature]: Standalone MM support

### ISSUE THREAD

**Issue by kenlautner** [microsoft/mu_crypto_release#46]
### Feature Overview

Currently the Shared crypto binaries produced are only availble for PEI, DXE and SMM.  With growing interest in Standalone MM having a binary for it makes sense.

### Solution Overview

1.  Generate a standalone MM binary for all the different Shared crypto flavors.
2.   Separate DXE and SMM crypto into their own fdf files.
3.   Include a Standalone MM fdf file.
4.  Update the publishing script to also publish the new Standalone MM binaries.

### Urgency

Medium

### Are you going to implement the feature request?

Someone else needs to implement the feature

### Do you need maintainer feedback?

No maintainer feedback needed

**Comment by makubacki** [comment]
Shared crypto binaries in CryptoPkg in Mu Basecore updated to include the Standalone MM binary inhttps://github.com/microsoft/mu_basecore/pull/681.

**Comment by makubacki** [comment]
Shared crypto Standalone MM binary integrated with QEMU Q35 package in https://github.com/microsoft/mu_tiano_platforms/pull/822.
