### ISSUE TITLE
Investigate crypto providers other than openssl.

### ISSUE THREAD

**Issue by kenlautner** [microsoft/mu_crypto_release#49]
Our current crypto implementation is based on openssl and has been for years.  Unfortunately, we've had some issues continuing to use Openssl for this purpose such as:

1.  Binary size bloat
2.  Code readability and understanding
3.  Lack of ability to modify the codebase

For these reasons we're exploring different sources for our underlying crypto implementation.  Any findings/updates will be posted here.

**Comment by makubacki** [comment]
Reopening and adding to the backlog.
